### PR TITLE
Merge master

### PR DESCRIPTION
**Pull request by kpp**

### CODE REVIEW

**Comment by dvc94ch** [comment]
@kpp almost, still a build failure to fix

**Comment by kpp** [comment]
That's very strange. Got to be an old version of rustc somewhere. Can you restart the job?

**Comment by dvc94ch** [comment]
I think you need to update the ci config to a new rust version maybe?

**Comment by dvc94ch** [comment]
@kpp the build failure is still there, can you look into it?

**Comment by kpp** [comment]
We cache `~/.cargo` with `~/.cargo/bin/rustc` which can be of a previous stable version. I suppose it is fixed in https://github.com/libp2p/rust-libp2p/pull/2228.

**Pull request merged**
